Repository Tresjs/tres, pull requests merged in 2023-12, with the labels that each got.

#463 fix: force memory free allocation when disposing materials and geomeries
  playground/package.json
  playground/src/pages/empty.vue
  playground/src/pages/perf/AkuAku.vue
  playground/src/pages/perf/index.vue
  playground/src/router.ts
  pnpm-lock.yaml
  src/components/TresCanvas.vue
  src/composables/useTresContextProvider/index.ts
  src/core/nodeOps.ts
Labels: bug, performance

#468 chore(deps): update
  docs/package.json
  package.json
  playground/package.json
  pnpm-lock.yaml
Labels: dependencies

#465 feat: enable devtools
  CHANGELOG.md
  docs/package.json
  package.json
  playground/package.json
  playground/vite.config.ts
  pnpm-lock.yaml
  src/composables/useTresContextProvider/index.ts
  src/env.d.ts
  src/utils/perf.ts
Labels: feature, core

#438 fix: correct minor typos
  README.md
  docs/.vitepress/theme/components/LoveVueThreeJS.vue
  docs/api/instances-arguments-and-props.md
  docs/api/tres-canvas.md
  docs/blog/tres-ecosystem-update-8-11-23.md
  docs/guide/troubleshooting.md
  src/composables/useCamera/index.ts
  src/composables/useRaycaster/index.ts
Labels: docs, waiting for author

#479 feat: 474 vue chrome devtools plugin
  docs/package.json
  playground/package.json
  playground/src/components/TheExperience.vue
  playground/src/components/TheSphere.vue
  pnpm-lock.yaml
  src/components/TresCanvas.vue
  src/devtools/highlight.ts
  src/devtools/index.ts
  src/devtools/plugin.ts
  src/devtools/utils.ts
  src/utils/index.ts
  src/utils/perf.ts
Labels: core, dx, v4, devtools
