Repository Tresjs/tres, pull requests merged in 2024-05, with the labels that each got.

#655 docs: egghead cta
  docs/.vitepress/theme/custom.css
  docs/de/index.md
  docs/es/index.md
  docs/fr/index.md
  docs/index.md
  docs/nl/index.md
  docs/public/egghead-icon.png
  docs/public/egghead-icon.svg
  docs/zh/index.md
Labels: docs

#618 docs: correct incoherences in recipes
  .eslintrc-auto-import.json
  docs/.eslintrc-auto-import.json
  docs/cookbook/load-models.md
  docs/cookbook/load-textures.md
  docs/cookbook/text-3d.md
  docs/de/cookbook/load-models.md
  docs/es/cookbook/load-models.md
  docs/fr/cookbook/load-models.md
  docs/nl/cookbook/load-models.md
  docs/zh/cookbook/load-models.md
Labels: cookbook 🍳, needs-translations

#673 feat: 633 use loop
  .eslintrc-auto-import.json
  docs/.eslintrc-auto-import.json
  docs/.vitepress/config/en.ts
  docs/api/composables.md
  docs/cookbook/basic-animations.md
  docs/directives/v-always-look-at.md
  docs/directives/v-rotate.md
  playground/components.d.ts
  playground/src/components/AnimatedObjectUseUpdate.vue
  playground/src/components/DirectiveSubComponent.vue
  playground/src/components/FBOCube.vue
  playground/src/components/TakeOverLoopExperience.vue
  playground/src/components/TheSphere.vue
  playground/src/composables/useFBO.ts
  playground/src/pages/advanced/FBO.vue
  playground/src/pages/advanced/Memory.vue
  playground/src/pages/advanced/OnDemand.vue
  playground/src/pages/advanced/TakeOverLoop.vue
  playground/src/pages/advanced/index.vue
  playground/src/pages/basic/example.vue
  playground/src/pages/basic/index.vue
  playground/src/pages/index.vue
  playground/src/pages/misc/Directives.vue
  playground/src/router/index.ts
  playground/src/router/routes/advanced.ts
  playground/src/router/routes/index.ts
  playground/src/router/routes/misc.ts
  playground/src/router/routes/performance.ts
  playground/vite.config.ts
  src/components/TresCanvas.vue
  src/composables/index.ts
  src/composables/useLoop/index.ts
  src/composables/useRenderLoop/index.ts
  src/composables/useRenderer/index.ts
  src/composables/useTresContextProvider/index.ts
  src/core/loop.test.ts
  src/core/loop.ts
  src/directives/index.ts
  src/directives/vAlwaysLookAt.ts
  src/directives/vRotate.ts
  src/utils/createPriorityEventHook.test.ts
  src/utils/createPriorityEventHook.ts
  src/utils/index.ts
Labels: feature, p3-downstream-blocker, p3-significant

#683 fix: 682 helpers diposal error since latest threejs update `dispose` methods
  src/utils/index.ts
Labels: bug, v4, p4-important-bug

#685 fix: manual rendering blank
  playground/src/components/RenderingLogger.vue
  playground/src/components/TheSphere.vue
  playground/src/pages/advanced/OnDemand.vue
  playground/src/pages/advanced/manual/experience.vue
  playground/src/pages/advanced/manual/index.vue
  playground/src/pages/advanced/on-demand/experience.vue
  playground/src/pages/advanced/on-demand/index.vue
  playground/src/router/routes/advanced.ts
  src/composables/useRenderer/index.ts
Labels: v4, p4-important-bug, regression

#687 fix: 686 useloop callback state missing controls
  playground/auto-imports.d.ts
  playground/components.d.ts
  playground/src/components/AnimatedObjectUseUpdate.vue
  playground/src/components/DirectiveSubComponent.vue
  playground/src/components/TakeOverLoopExperience.vue
  playground/src/pages/models/PrimitivesModel.vue
  src/composables/useLoop/index.ts
  src/core/loop.ts
  src/index.ts
Labels: bug, types, v4, p4-important-bug, regression

#586 docs(cookbook): "Advanced Animations" cookbook recipe
  docs/.vitepress/config/de.ts
  docs/.vitepress/config/en.ts
  docs/.vitepress/config/es.ts
  docs/cookbook/advanced-animations.md
  docs/de/cookbook/advanced-animations.md
  docs/es/cookbook/advanced-animations.md
  docs/public/recipes/advanced-animations.png
Labels: cookbook 🍳

#705 chore: update stackblitz minimal reproduction on github templates
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: docs, p1-chore
