Repository Tresjs/tres, pull requests merged in 2024-03, with the labels that each got.

#579 fix: `nodeOps` is now a function
  playground/src/components/MultipleCanvas.vue
  playground/src/pages/multiple.vue
  src/components/TresCanvas.vue
  src/core/nodeOps.ts
  src/core/nodeOpts.test.ts
  src/core/renderer.ts
Labels: bug

#589 docs: fix playground link navigation
  docs/.vitepress/config/de.ts
  docs/.vitepress/config/en.ts
  docs/.vitepress/config/es.ts
  docs/de/guide/index.md
  docs/es/guide/index.md
  docs/guide/index.md
  docs/public/tresjs-lab.png
Labels: docs

#550 docs: chinese translations
  docs/.vitepress/config/index.ts
  docs/.vitepress/config/zh.ts
  docs/zh/advanced/caveats.md
  docs/zh/advanced/extending.md
  docs/zh/advanced/primitive.md
  docs/zh/api/composables.md
  docs/zh/api/events.md
  docs/zh/api/instances-arguments-and-props.md
  docs/zh/api/tres-canvas.md
  docs/zh/cookbook/basic-animations.md
  docs/zh/cookbook/groups.md
  docs/zh/cookbook/index.md
  docs/zh/cookbook/lights-shadows.md
  docs/zh/cookbook/load-models.md
  docs/zh/cookbook/load-textures.md
  docs/zh/cookbook/orbit-controls.md
  docs/zh/cookbook/shaders.md
  docs/zh/cookbook/text-3d.md
  docs/zh/debug/devtools.md
  docs/zh/directives/v-always-look-at.md
  docs/zh/directives/v-distance-to.md
  docs/zh/directives/v-light-helper.md
  docs/zh/directives/v-log.md
  docs/zh/guide/getting-started.md
  docs/zh/guide/index.md
  docs/zh/guide/migration-guide.md
  docs/zh/guide/nuxt.md
  docs/zh/guide/troubleshooting.md
  docs/zh/guide/your-first-scene.md
  docs/zh/index.md
  docs/zh/team.md
Labels: docs, i18n

#602 fix: refactor nodeOps to return methods at the end of the function
  src/core/nodeOps.ts
Labels: bug

#604 fix: explicitely add `@vue/devtools-api` dep to package.json
  package.json
  pnpm-lock.yaml
Labels: bug, devtools

#510 fix(useLogger): remove '<empty string>', allow any args/string substitution
  src/composables/useLogger.ts
Labels: p1-chore

#608 fix: do not lowercase pierced props
  playground/src/pages/basic/PiercedProps.vue
  playground/src/router/routes/basic.ts
  src/core/nodeOps.ts
  src/core/nodeOpts.test.ts
Labels: test, playground, v4, breaking-change
