Repository Tresjs/tres, pull requests merged in 2024-07, with the labels that each got.

#753 chore: sponsorkit
  .github/workflows/sponsorkit.yml
  .gitignore
  README.md
  eslint.config.js
  package.json
  pnpm-lock.yaml
  sponsorkit.config.ts
  sponsorkit/.cache.json
  sponsorkit/sponsors.json
  sponsorkit/sponsors.png
  sponsorkit/sponsors.svg
Labels: docs

#731 fix: group should recursive search for child elements (#728)
  src/composables/useRaycaster/index.ts
  src/composables/useTresEventManager/index.ts
Labels: bug, p5-urgent-bug, regression

#761 chore(ci): update `pnpm/action-setup` to v4
  .github/workflows/lint.yml
  .github/workflows/sponsorkit.yml
  .github/workflows/test.yml
Labels: p1-chore

#749 fix: attach detach
  playground/src/pages/advanced/materialArray/index.vue
  playground/src/pages/models/RiggedModel.vue
  playground/src/pages/models/RiggedModel/UgglyBunny.vue
  playground/src/pages/models/RiggedModel/index.vue
  playground/src/router/routes/advanced.ts
  playground/src/router/routes/models.ts
  src/core/nodeOps.test.ts
  src/core/nodeOps.ts
  src/types/index.ts
  src/utils/index.test.ts
  src/utils/index.ts
  src/utils/is.test.ts
  src/utils/is.ts
  src/utils/nodeOpsUtils.ts
Labels: p4-important-bug

#740 feat: (devtools) add userData to inspectable properties
  src/devtools/plugin.ts
Labels: waiting for author, devtools, p2-nice-to-have

#764 fix(primitive): implement as proxy to avoid breaking references
  docs/advanced/primitive.md
  playground/src/pages/advanced/disposal/index.vue
  playground/src/pages/issues/701-cientos-v4/TheExperience.vue
  playground/src/pages/issues/701-cientos-v4/index.vue
  playground/src/pages/issues/701/TheExperience.vue
  playground/src/pages/issues/701/index.vue
  playground/src/pages/issues/749/TheExperience.vue
  playground/src/pages/issues/749/index.vue
  playground/src/router/routes/advanced.ts
  playground/src/router/routes/issues.ts
  src/core/nodeOps.test.ts
  src/core/nodeOps.ts
  src/types/index.ts
  src/utils/index.ts
  src/utils/is.ts
  src/utils/primitive/createRetargetingProxy.test.ts
  src/utils/primitive/createRetargetingProxy.ts
Labels: p5-urgent-bug, needs-documentation

#767 fix: localstate for objects with events and manual register/unregister from nodeOps using ctx
  package.json
  playground/src/pages/events/DynamicObjects.vue
  playground/src/pages/events/index.vue
  playground/src/router/routes/events.ts
  pnpm-lock.yaml
  src/components/TresCanvas.vue
  src/composables/useTresContextProvider/index.ts
  src/composables/useTresEventManager/index.ts
  src/core/nodeOps.ts
Labels: bug, p4-important-bug

#771 chore: remove old pointer event handler composable
  docs/package.json
  package.json
  playground/package.json
  pnpm-lock.yaml
  src/composables/index.ts
  src/composables/usePointerEventHandler/index.ts
  src/composables/useRaycaster/index.ts
  src/composables/useTresContextProvider/index.ts
  src/composables/useTresEventManager/index.ts
  src/core/nodeOps.ts
  src/utils/index.ts
Labels: p1-chore

#781 fix(types): `useLoader` generics
  playground/src/composables/useFBX.ts
  playground/src/composables/useGLTF.ts
  playground/src/pages/index.vue
  playground/src/pages/loaders/fbx-loader/TheExperience.vue
  playground/src/pages/loaders/fbx-loader/TheModel.vue
  playground/src/pages/loaders/fbx-loader/index.vue
  playground/src/pages/loaders/gltf-loader/TheExperience.vue
  playground/src/pages/loaders/gltf-loader/TheModel.vue
  playground/src/pages/loaders/gltf-loader/index.vue
  playground/src/router/routes/index.ts
  playground/src/router/routes/loaders.ts
  src/composables/useLoader/index.ts
Labels: bug, types, p3-minor-bug

#788 fix: remove on demand invalidation warning
  src/composables/useTresContextProvider/index.ts
Labels: bug, p3-downstream-blocker

#790 chore(cookbook): 762 recipe using tweakpane
  docs/.vitepress/config/en.ts
  docs/cookbook/tweakpane.md
  docs/package.json
  docs/public/recipes/tweakpane.png
  pnpm-lock.yaml
Labels: cookbook 🍳

#793 fix: 792 directionallighthelpers breaks devtools
  src/devtools/plugin.ts
  src/utils/is.ts
  src/utils/perf.ts
Labels: bug, p4-important-bug
