Repository Tresjs/tres, pull requests merged in 2024-09, with the labels that each got.

#809 fix: 785 vscode intellisense autocompletion not getting tres components props
  .github/workflows/pkg.pr.new.yml
  docs/advanced/performance.md
  docs/advanced/primitive.md
  package.json
  playground/.eslintrc-auto-import.json
  playground/components.d.ts
  playground/vue/.eslintrc-auto-import.json
  playground/vue/package.json
  playground/vue/src/pages/basic/index.vue
  playground/vue/src/pages/issues/701/TheExperience.vue
  playground/vue/tsconfig.json
  pnpm-lock.yaml
  src/composables/useLogger.ts
  src/composables/useTresEventManager/index.ts
  src/core/nodeOps.test.ts
  src/core/nodeOps.ts
  src/env.d.ts
  src/types/index.ts
  src/utils/createPriorityEventHook.test.ts
  src/utils/index.ts
  src/utils/is.ts
Labels: bug, types, p4-important-bug

#819 chore(ci): automerge renovate branches minors and patches
  renovate.json
Labels: p1-chore

#757 feat(app): 680 UseTexture composable as component
  docs/advanced/performance.md
  docs/advanced/primitive.md
  docs/api/composables.md
  docs/es/api/composables.md
  playground/vue/src/pages/basic/Textures.vue
  playground/vue/src/pages/issues/701/TheExperience.vue
  playground/vue/src/router/routes/basic.ts
  pnpm-lock.yaml
  src/composables/index.ts
  src/composables/useLogger.ts
  src/composables/useTexture/component.vue
  src/composables/useTresEventManager/index.ts
  src/core/nodeOps.test.ts
  src/core/nodeOps.ts
  src/env.d.ts
  src/types/index.ts
  src/utils/createPriorityEventHook.test.ts
  src/utils/index.ts
  src/utils/is.ts
Labels: feature, p2-nice-to-have, needs-documentation

#834 chore: remove husky and fix back linter
  .husky/install.mjs
  .husky/pre-push
  docs/.vitepress/theme/components/LocalOrbitControls.vue
  docs/.vitepress/theme/components/StackBlitzEmbed.vue
  docs/.vitepress/theme/index.ts
  package.json
  playground/nuxt/components/EnvironmentLocal.vue
  playground/vue/src/composables/useFBX.ts
  playground/vue/src/composables/useGLTF.ts
  playground/vue/src/pages/advanced/devicePixelRatio/index.vue
  playground/vue/src/pages/advanced/fbo/useFBO.ts
  playground/vue/src/pages/basic/Lights.vue
  playground/vue/src/pages/basic/ready/index.vue
  playground/vue/src/pages/cameras/multipleCameras/index.vue
  playground/vue/src/pages/events/index.vue
  playground/vue/src/pages/issues/701/TheExperience.vue
  pnpm-lock.yaml
  src/components/TresCanvas.vue
  src/composables/useCamera/index.ts
  src/composables/useLoader/index.ts
  src/composables/useLoop/index.ts
  src/composables/useRaycaster/index.ts
  src/composables/useRenderLoop/index.ts
  src/composables/useRenderer/index.ts
  src/composables/useSizes/index.ts
  src/composables/useTexture/component.vue
  src/composables/useTexture/index.ts
  src/composables/useTresContextProvider/index.ts
  src/composables/useTresEventManager/index.ts
  src/composables/useTresReady/createReadyEventHook/index.ts
  src/composables/useTresReady/index.ts
  src/core/catalogue.ts
  src/core/loop.test.ts
  src/core/loop.ts
  src/core/nodeOps.test.ts
  src/core/nodeOps.ts
  src/devtools/plugin.ts
  src/directives/vDistanceTo.ts
  src/directives/vLightHelper.ts
  src/utils/createPriorityEventHook.ts
  src/utils/index.ts
  src/utils/normalize.ts
  src/utils/test-utils.ts
Labels: p1-chore

#846 fix: rollback to v6 of `@vue/devtools-api`
  docs/.vitepress/config/de.ts
  docs/.vitepress/config/en.ts
  docs/.vitepress/config/es.ts
  docs/.vitepress/config/fr.ts
  docs/.vitepress/config/nl.ts
  docs/.vitepress/config/zh.ts
  package.json
  pnpm-lock.yaml
Labels: p5-urgent-bug

#806 feat: pass all provides down to custom renderer
  docs/api/tres-canvas.md
  playground/.eslintrc-auto-import.json
  playground/vue/components.d.ts
  playground/vue/src/App.vue
  playground/vue/src/components/ProvideBridge.vue
  playground/vue/src/pages/basic/index.vue
  playground/vue/src/pages/issues/732/ProvideInjectExperience.vue
  playground/vue/src/pages/issues/732/SubComponentWithInject.vue
  playground/vue/src/pages/issues/732/SubVueComponentWithInject.vue
  playground/vue/src/pages/issues/732/index.vue
  playground/vue/src/router/routes/issues.ts
  src/components/TresCanvas.vue
Labels: feature
