Repository Tresjs/tres, pull requests merged in 2025-02, with the labels that each got.

#920 docs: remove deprecated v-always-look-at and v-rotate directives
  docs/.vitepress/config/de.ts
  docs/.vitepress/config/es.ts
  docs/.vitepress/config/fr.ts
  docs/.vitepress/config/nl.ts
  docs/.vitepress/config/zh.ts
  docs/de/directives/v-always-look-at.md
  docs/directives/v-always-look-at.md
  docs/directives/v-rotate.md
  docs/es/directives/v-always-look-at.md
  docs/fr/directives/v-always-look-at.md
  docs/nl/directives/v-always-look-at.md
  docs/zh/directives/v-always-look-at.md
  playground/vue/src/pages/basic/Lights.vue
Labels: p1-chore

#916 fix: remove camera warning log on default camera creation
  src/components/TresCanvas.vue
Labels: p2-nice-to-have

#918 fix: improve Object3D disposal method
  src/utils/index.ts
Labels: p4-important-bug

#924 fix: typescript build issues utils
  src/devtools/plugin.ts
  src/utils/index.ts
  src/utils/primitive/createRetargetingProxy.ts
Labels: bug

#929 fix: revert typescript changes for use dpr
  src/utils/index.ts
Labels: p1-chore

#930 fix: revert improve type safety in retargeting proxy setter
  src/utils/primitive/createRetargetingProxy.ts
Labels: bug

#942 chore(netlify): configure Node.js version and disable Corepack integr…
  netlify.toml
Labels: bug, docs

#948 docs: correct link to tweakpane in english docs
  docs/cookbook/tweakpane.md
Labels: docs
