Repository Tresjs/tres, pull requests merged in 2025-06, with the labels that each got.

#1013 feat: 1012 add context inspector devtools
  src/components/TresCanvas.vue
  src/devtools/inspectorHandlers.ts
  src/devtools/plugin.ts
  src/devtools/types.ts
Labels: feature, p3-significant

#1026 feat!: 997 refactor events 2
  package.json
  playground/vue/.eslintrc-auto-import.json
  playground/vue/package.json
  playground/vue/src/pages/events/groups/index.vue
  playground/vue/src/pages/events/index.vue
  playground/vue/src/pages/events/propagation/Box.vue
  playground/vue/src/pages/events/propagation/index.vue
  pnpm-lock.yaml
  src/components/TresCanvas.vue
  src/composables/index.ts
  src/composables/useCamera/index.ts
  src/composables/useEventManager/index.ts
  src/composables/useLoop/index.ts
  src/composables/useRaycaster/index.ts
  src/composables/useRenderer/useRendererManager.ts
  src/composables/useTres/index.ts
  src/composables/useTresContextProvider/index.ts
  src/composables/useTresEventManager/index.ts
  src/core/nodeOps.ts
  src/types/index.ts
  src/utils/index.ts
  src/utils/pointerEvents.ts
Labels: feature, breaking-change

#1022 feat: 982 refactor userenderer
  docs/api/composables.md
  playground/vue/src/pages/advanced/devicePixelRatio/index.vue
  playground/vue/src/pages/advanced/takeOverRender/TakeOverRenderExperience.vue
  playground/vue/src/pages/basic/index.vue
  src/components/TresCanvas.vue
  src/composables/useRenderer/const.ts
  src/composables/useRenderer/useRendererManager.ts
  src/composables/useTres/index.ts
  src/composables/useTresContextProvider/index.ts
  src/core/loop.ts
  src/devtools/inspectorHandlers.ts
Labels: feature, breaking-change

#1029 feat: webgpu native support
  playground/vue/src/pages/advanced/webGPU/HologramCube.vue
  playground/vue/src/pages/advanced/webGPU/index.vue
  playground/vue/src/router/routes/advanced.ts
  src/components/TresCanvas.vue
  src/composables/useRenderer/useRendererManager.ts
  src/composables/useTres/index.ts
  src/composables/useTresContextProvider/index.ts
  src/devtools/inspectorHandlers.ts
Labels: feature, p3-significant

#1035 refactor: useLoop and useRenderLoop refactoring
  playground/vue/src/App.vue
  playground/vue/src/components/AnimatedObjectUseUpdate.vue
  playground/vue/src/components/BlenderCube.vue
  playground/vue/src/components/LocalOrbitControls.vue
  playground/vue/src/components/TheSphere.vue
  playground/vue/src/pages/advanced/fbo/FBOCube.vue
  playground/vue/src/pages/advanced/fbo/index.vue
  playground/vue/src/pages/advanced/fbo/useFBO.ts
  playground/vue/src/pages/advanced/manual/experience.vue
  playground/vue/src/pages/advanced/takeOverRender/TakeOverRenderExperience.vue
  playground/vue/src/pages/advanced/webGPU/index.vue
  playground/vue/src/pages/basic/Multiple.vue
  playground/vue/src/pages/basic/PiercedProps.vue
  playground/vue/src/pages/basic/Primitives.vue
  playground/vue/src/pages/basic/index.vue
  playground/vue/src/pages/events/DynamicObjects.vue
  playground/vue/src/pages/events/FpsDropsReproduction.vue
  playground/vue/src/pages/loaders/fbx-loader/TheExperience.vue
  playground/vue/src/pages/loaders/gltf-loader/TheExperience.vue
  playground/vue/src/pages/loaders/multiple-models/TheExperience.vue
  playground/vue/src/pages/loaders/texture-loader/TheExperience.vue
  playground/vue/src/pages/misc/BrownianDistribution.vue
  playground/vue/src/pages/misc/BrownianDistributionExperience.vue
  playground/vue/src/pages/misc/use-graph/index.vue
  pnpm-lock.yaml
  src/components/TresCanvas.vue
  src/composables/index.ts
  src/composables/useCreateRafLoop/index.ts
  src/composables/useEventManager/index.ts
  src/composables/useLoop/index.ts
  src/composables/useLoop/useLoop.test.ts
  src/composables/useRenderLoop/index.ts
  src/composables/useRenderer/useRendererManager.ts
  src/composables/useTres/index.ts
  src/composables/useTresContextProvider/index.ts
  src/core/loop.test.ts
  src/core/loop.ts
  src/index.ts
  src/types/index.ts
  src/utils/createPriorityEventHook.ts
  vite.config.ts
Labels: feature, breaking-change

#1041 fix: build-graph utility types
  package.json
  playground/vue/src/composables/usePocGLTF.ts
  pnpm-lock.yaml
  src/composables/useGraph/index.ts
  src/types/index.ts
  src/utils/graph.ts
Labels: bug, types, p3-minor-bug

#1044 refactor: 1043 render function triggers too often
  playground/vue/src/pages/advanced/attachPostProcessing/Effects.vue
  playground/vue/src/pages/advanced/takeOverRender/TakeOverRenderExperience.vue
  src/composables/useCreateRafLoop/index.ts
  src/composables/useLoop/index.ts
  src/composables/useLoop/useLoop.test.ts
  src/composables/useRenderer/useRendererManager.ts
Labels: bug

#1042 refactor: 983 refactor usetrescontextprovider to use createinjectionstate
  src/components/TresCanvas.vue
  src/composables/index.ts
  src/composables/useTresContextProvider/index.ts
Labels: feature
