Repository Tresjs/tres, pull requests merged in 2025-04, with the labels that each got.

#975 feat: 974-createsetup-devtools
  playground/vue/src/pages/events/index.vue
  src/composables/useTresContextProvider/index.ts
  src/devtools/plugin.ts
  src/devtools/setupDevtools.ts
  src/utils/perf.ts
Labels: p1-chore, v5

#977 feat: 974-vue-devtools-api-v7
  package.json
  playground/vue/package.json
  playground/vue/vite.config.ts
  pnpm-lock.yaml
  src/devtools/plugin.ts
Labels: feature, p2-nice-to-have

#991 refactor: reorganize devtools setup and imports
  src/components/TresCanvas.vue
  src/composables/useTresContextProvider/index.ts
  src/devtools/plugin.ts
  src/devtools/setupDevtools.ts
Labels: p1-chore

#993 refactor!: 979 move renderer logic from usetrescontextprovider to userenderer 2
  docs/.vitepress/theme/components/BlenderCube.vue
  docs/advanced/attach.md
  docs/advanced/performance.md
  docs/api/composables.md
  docs/cookbook/orbit-controls.md
  playground/vue/src/pages/advanced/devicePixelRatio/index.vue
  playground/vue/src/pages/advanced/manual/experience.vue
  playground/vue/src/pages/advanced/on-demand/experience.vue
  playground/vue/src/pages/advanced/suspense/AsyncComponent.vue
  playground/vue/src/pages/advanced/suspense/index.vue
  playground/vue/src/pages/advanced/takeOverRender/TakeOverRenderExperience.vue
  src/components/TresCanvas.vue
  src/composables/index.ts
  src/composables/useLoop/index.ts
  src/composables/useRaycaster/index.ts
  src/composables/useRenderer/useRendererManager.ts
  src/composables/useSizes/index.ts
  src/composables/useTresContextProvider/index.ts
  src/composables/useTresReady/index.ts
  src/core/loop.ts
  src/devtools/plugin.ts
  src/utils/index.ts
Labels: p3-significant, breaking-change

#999 refactor!: 992 removal of emit from usetrescontextprovider composable
  src/components/TresCanvas.vue
  src/composables/useLoader/component.vue
  src/composables/useTresContextProvider/index.ts
  src/composables/useTresEventManager/index.ts
  src/types/index.ts
Labels: breaking-change
