Repository Tresjs/tres, pull requests merged in 2025-05, with the labels that each got.

#1008 feat!: 986 remove usetexture
  docs/api/composables.md
  docs/cookbook/load-textures.md
  src/composables/index.ts
  src/composables/useTexture/component.vue
  src/composables/useTexture/index.ts
  src/composables/useTexture/useTexture.test.ts
Labels: p3-downstream-blocker, breaking-change

#1006 fix(patchProp): harden props inference
  src/core/nodeOps.test.ts
  src/core/nodeOps.ts
  src/utils/is.ts
Labels: p3-minor-bug

#1004 refactor!: context camera is now a state
  playground/vue/src/pages/cameras/OrthographicCamera.vue
  playground/vue/src/pages/cameras/PerspectiveCamera.vue
  playground/vue/src/pages/cameras/index.vue
  playground/vue/src/pages/cameras/multipleCameras/TheCameraOperator.vue
  playground/vue/src/pages/cameras/multipleCameras/index.vue
  playground/vue/src/router/routes/cameras.ts
  src/components/TresCanvas.vue
  src/composables/index.ts
  src/composables/useCamera/index.ts
  src/composables/useRaycaster/index.ts
  src/composables/useRenderer/useRendererManager.ts
  src/composables/useTresContextProvider/index.ts
  src/core/loop.ts
  src/core/nodeOps.test.ts
  src/core/nodeOps.ts
  src/types/index.ts
  src/utils/index.ts
  src/utils/is.ts
Labels: p3-significant, breaking-change

#1011 fix: make sure key is camelCase when reached else on conditional
  docs/contribute/contributing.md
  playground/vue/components.d.ts
  playground/vue/src/components/LocalOrbitControls.vue
  playground/vue/src/pages/basic/PiercedProps.vue
  src/core/nodeOps.ts
Labels: bug
